name: my_pub_package
version: 0.0.1
homepage: http://foo.com
description: >
  Just a toy, never see the light of day
dependencies:
# custom <my_pub_package dependencies>
# end <my_pub_package dependencies>

dev_dependencies:
  hop: ">=0.27.0"

# custom <my_pub_package dev dependencies>
# end <my_pub_package dev dependencies>

transformers:
# custom <my_pub_package transformers>
# end <my_pub_package transformers>

